# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName(_fromUtf8("main"))
        main.resize(800, 600)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(main)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.iconView = QtGui.QListWidget(main)
        self.iconView.setMinimumSize(QtCore.QSize(128, 0))
        self.iconView.setMaximumSize(QtCore.QSize(128, 16777215))
        self.iconView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.iconView.setIconSize(QtCore.QSize(48, 48))
        self.iconView.setMovement(QtGui.QListView.Static)
        self.iconView.setViewMode(QtGui.QListView.IconMode)
        self.iconView.setUniformItemSizes(True)
        self.iconView.setObjectName(_fromUtf8("iconView"))
        self.horizontalLayout.addWidget(self.iconView)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabLabel = QtGui.QLabel(main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabLabel.sizePolicy().hasHeightForWidth())
        self.tabLabel.setSizePolicy(sizePolicy)
        self.tabLabel.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tabLabel.setFont(font)
        self.tabLabel.setMargin(6)
        self.tabLabel.setObjectName(_fromUtf8("tabLabel"))
        self.verticalLayout.addWidget(self.tabLabel)
        self.scrollArea = QtGui.QScrollArea(main)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 654, 499))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.contentLayout = QtGui.QFormLayout(self.scrollAreaWidgetContents)
        self.contentLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.contentLayout.setMargin(0)
        self.contentLayout.setObjectName(_fromUtf8("contentLayout"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(4, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.line = QtGui.QFrame(main)
        self.line.setMinimumSize(QtCore.QSize(0, 2))
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(-1)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.advancedButton = QtGui.QPushButton(main)
        self.advancedButton.setCheckable(True)
        self.advancedButton.setObjectName(_fromUtf8("advancedButton"))
        self.horizontalLayout_2.addWidget(self.advancedButton)
        spacerItem1 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.okButton = QtGui.QPushButton(main)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout_2.addWidget(self.okButton)
        self.applyButton = QtGui.QPushButton(main)
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.horizontalLayout_2.addWidget(self.applyButton)
        self.cancelButton = QtGui.QPushButton(main)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.retranslateUi(main)
        QtCore.QObject.connect(self.okButton, QtCore.SIGNAL(_fromUtf8("clicked()")), main.ok)
        QtCore.QObject.connect(self.applyButton, QtCore.SIGNAL(_fromUtf8("clicked()")), main.apply)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), main.cancel)
        QtCore.QObject.connect(self.advancedButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), main.toggleAdvanced)
        QtCore.QObject.connect(self.iconView, QtCore.SIGNAL(_fromUtf8("currentItemChanged(QListWidgetItem*,QListWidgetItem*)")), main.tabChanged)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        main.setWindowTitle(QtGui.QApplication.translate("main", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tabLabel.setText(QtGui.QApplication.translate("main", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.advancedButton.setToolTip(QtGui.QApplication.translate("main", "Show or hide advanced options.", None, QtGui.QApplication.UnicodeUTF8))
        self.advancedButton.setText(QtGui.QApplication.translate("main", "&Show advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("main", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("main", "&Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setToolTip(QtGui.QApplication.translate("main", "Close the window and cancel all changes made.", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("main", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))

